import Head from "next/head";
import { useEffect, useState } from "react";
import PublicApi from "../apis/PublicApi";
import Analytics from "../components/Analytics";
import Footer from "../components/Footer";
import GoToTheMoon from "../components/GoToTheMoon";
import Hero from "../components/Hero";
import HotKeyWordList from "../components/HotKeyWordList";
import Navbar from "../components/Navbar";
import Newsletter from "../components/Newsletter";
import Study from "../components/Study";
import TopSale from "../components/TopSale";
import { PublicLayout } from "../layouts/public";
import { PublicMainLayout } from "../layouts/publicmain";

export default function Home() {
  const [products,setProducts] = useState([]);
  useEffect(() =>{
    PublicApi.getProducts('all','').then(res =>{
        console.log(res.data);
        setProducts(res.data)
    }).catch(error =>{
        Notify.failure(error);
    });
},[])
  return (
    <div>
      <Head>
        <title>Space0 - Shop bản quyền</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=''>
      <Hero /> 
      <HotKeyWordList />
      <TopSale products = {products}/>
      <Analytics />
      <Newsletter />
      <Study products = {products}/>
      <Study products = {products}/>
      <GoToTheMoon />
      </main>
    </div>
  );
}
Home.Layout = PublicMainLayout
