import Head from "next/head";
import Analytics from "../components/Analytics";
import Footer from "../components/Footer";
import GoToTheMoon from "../components/GoToTheMoon";
import Hero from "../components/Hero";
import HotKeyWordList from "../components/HotKeyWordList";
import Navbar from "../components/Navbar";
import Newsletter from "../components/Newsletter";
import Study from "../components/Study";
import TopSale from "../components/TopSale";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Space0 - Shop bản quyền</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=''>
      <Navbar />
      <Hero />
      <HotKeyWordList />
      <TopSale />
      <Analytics />
      <Newsletter />
      <Study />
      <Study />
      <Footer />
      <GoToTheMoon />
      </main>
    </div>
  );
}
